### ISSUE TITLE
options not working (except for errorCorrectionLevel)

### ISSUE THREAD

**Issue by wkamir** [soldair/node-qrcode#102]
Thanks to everyone for this nice and easy to use library!

I just tried a basic example (express, backend):

```
var qrcode = require('qrcode');
app.use('/qr', (req, res) => {
  var opts = {
    errorCorrectionLevel: 'H',
    rendererOpts: {
      color: {
        dark: '#00f',
        light: '#fff'
      },
      quality: 0.92
    }
  }

  qrcode.toDataURL('some data string', opts, (err, url) => {
    res.end("<!DOCTYPE html/><html><head><title>node-qrcode</title></head><body><img src='" + url + "'/></body></html>")
  });
});
```

I was expecting to have a blue on white qr code generated, but it came out black on white...
I tried to modify different settings (image type, scale, etc.) but it seems that those settings don't have any effect. The only setting that seems to work is the "errorCorrectionLevel".

When I go from "H" to "L" I can clearly see a difference.

Am I missing something obvious?

Thanks,
Wolfgang

**Comment by vigreco** [comment]
Hi @wkamir,

`color` is not a property of `rendererOpts`, you should move it at the same level of `errorCorrectionLevel` as for all other options.

```javascript
var opts = {
    errorCorrectionLevel: 'H',
    color: {
      dark: '#00f',
      light: '#fff'
    },
    scale: 10,
    margin: 10,
    ...
  }
```

`rendererOpts` is only used to fine tuning the renderer settings, like deflate compression for pngs or image quality for jpegs. In most cases there's no need to set these values. 

If you are using the lib with node/express only the settings for the png renderer are available, which are:
[rendererOpts.deflateLevel](https://github.com/soldair/node-qrcode#rendereroptsdeflatelevel-png-only)
[rendererOpts.deflateStrategy](https://github.com/soldair/node-qrcode#rendereroptsdeflatestrategy-png-only)

If you are using it in browser instead, you can only set the quality of jpeg or webp images with:
[rendererOpts.quality](rendererOpts.quality)

So, in your example code `rendererOpts.quality` has no effect since is not applicable to the png renderer.

Hope it helps 😄

**Comment by wkamir** [comment]
:grin: Sure helps.

Thanks a lot!
