### ISSUE TITLE
[Proposal] Support for promises and through that Async/Await for NodeJS

### ISSUE THREAD

**Issue by Favna** [soldair/node-qrcode#107]
As the title suggests I would strongly recommend creating support for [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for the NodeJS part of this module due to the power and future proofing that this grants the package as a whole. 

Once promise support is added we can also directly use the package asynchronously, an example code snippet of such would be:

```js
var qr = require('qrcode');

const qrgen = async function(url) {
    const qrurl = await qr.toDataURL(url, {
        'errorCorrectionLevel': 'M'
    })

    if (qrurl) {
        return qrurl
    }

    return console.error('An error occured encoding the data to a QR code')
}
```

You can read more on promises and async/await code on this great article: https://medium.freecodecamp.org/javascript-from-callbacks-to-async-await-1cc090ddad99

Lastly to give a full implementation of the code snippet above to really clarify the use I have this snippet:

```js
var qr = require('qrcode');
var imgur = require('imgur');

const qrgen = async function(url) {
    const qrurl = await qr.toDataURL(url, {
        'errorCorrectionLevel': 'M'
    })

    if (qrurl) {
        const image = await imgur.uploadBase64(qrurl.slice(22));

        console.log(image.data.link) // see note below
    }

    return console.error('An error occured encoding the data to a QR code')
}
```
note: this is the QR image we just generated uploaded to imgur to use in any way we want. For example in my personal use case I'd like to send this URL as a message to the Discord chat that a command to generate a QR code is issued as seen in my bot's code here: https://github.com/Favna/Ribbon/blob/master/src/commands/links/qrgen.js

**Comment by tastypackets** [comment]
I agree.

I put a Qr code generator in a promise so I can use it in a similar fashion, but it would be nice if the library had promises out of the box so I don't have to do this.

**Comment by vigreco** [comment]
I definitely agree on this.

Using cb function can be inconvenient especially when using ES6/ES7 syntax.
I had proposed this sometime ago too (#56), but till now it had a low priority since is quite easy to workaround the problem by wrapping the qrcode api in a Promise like you did.

I don't think we'll going to completely replace callbacks func with Promise anytime soon, but surely we may make both of them available.
At least for node, it should be quite easy to implement now since we dropped support for versions < 4.
For browsers we also support IE9+, so it will need a few more checks.

I had a local branch with an initial implementation of this, I'll try to refresh it and push a PR within next days.

@soldair what do you think?

**Comment by soldair** [comment]
As more and more folks expect this to work that way it would be nice to expose promise wrapped ends for people to call and treat it as a first class way to use the lib. Excited to see where we end up. :)

**Comment by vigreco** [comment]
`v1.2.0` released with support for Promises 😃
