### ISSUE TITLE
Cannot import QRCode

### ISSUE THREAD

**Issue by ArtworkAD** [soldair/node-qrcode#120]
Hey, 

I am using node v7.9 and typescript. I cannot correctly import the library (I did install the @types):

    import { QRCode } from 'qrcode';

imports just `export interface QRCode`. To get the methods I do:

    import * as QRCode  from 'qrcode';

But

    QRCode.toDataURL("foobar");

is giving me the error: `Expected 2-4 arguments but got 1`, which is not inline with your examples. Event if I try

    QRCode.toDataURL("adsa", { verison: 2 }).then();

it wants me to specify the callback, and says: `property then does not exist in type void`.

**Comment by soldair** [comment]
we don't maintain typings for this library. It seems a third party does though. 
My guess is they are not up to date because we recently released promise support for qr code.

I think you will either have to call the function as you have defined in your typings because you are using typescript or update the type definitions to match this package's interface.

**Comment by ArtworkAD** [comment]
@soldair thanks, I will update the typings.
