### ISSUE TITLE
Option for svg or png image in center of qr

### ISSUE THREAD

**Issue by SimonFricker** [soldair/node-qrcode#122]

**Comment by soldair** [comment]
if you do this in the browser we return the canvas object and you can use the canvas apis to drawImage right in the middle if you like. on the server you can use anyone of the available image editing npm packages to write an image to the center.

if you do make sure you use max error correction. 

It's unlikely that we'll add this directly to the qr code library because it wont always generate a scan-able qrcode. qrcodes are also interpreted in black and white so in good light you can make an image 50% darker or 50% lighter if its a square or not and have your whole code be a nice image
