### ISSUE TITLE
Uint32Array error on android devices

### ISSUE THREAD

**Issue by andrescabana86** [soldair/node-qrcode#14]
when i load on client side the script /assets/qrcode.js on line 651 i have this console error

Uncaught ReferenceError: Uint32Array is not defined

can you explain me whats the problem what im doing wrong?

**Comment by vigreco** [comment]
Not sure why [this](https://github.com/soldair/node-qrcode/blob/master/lib/qrcode.js#L40) and [this](https://github.com/soldair/node-qrcode/blob/master/lib/qrcode-draw.js#L34) are there.
Uint32Array is never used due to a bug in the if condition, but it can't be used anyway since the rest of the code doesn't expect a typed array.
We should probably use just a simple Array here, since we don't take any advantage of using an Uint32Array.

@soldair I'll send a PR if you agree.

**Comment by soldair** [comment]
I agree :)
