### ISSUE TITLE
toDataURL get error in Safari (IOS9)

### ISSUE THREAD

**Issue by yu521088** [soldair/node-qrcode#195]
I get an error on IOS 9, says "Cross-origin image load denied by Cross-Origin Resource Sharing policy."

i checked the code and found that this code in `renderToDataURL` method in `canvas.js` throw an error:
`return canvasEl.toDataURL(type, rendererOpts.quality)`

**Comment by soldair** [comment]
data urls for image srcs must violate your sites CSP.

either 
- change it. 
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
- use canvas to display the image directly instead of the uri
  - `QRCode.toCanvas(canvas, 'sample text',......`
- or switch to SVG to display the image.
  - `QRCode.toString(text, {type:'svg'}, [cb(error, string)])`
  - you can just put it in your page with innerHtml etc https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
