### ISSUE TITLE
Feature Request: Add a umd format output

### ISSUE THREAD

**Issue by JounQin** [soldair/node-qrcode#200]
As title, I can create a PR for it if you like.

Additional, it would be greater if this module can be wrote as ES Module or TypeScript.

**Comment by soldair** [comment]
yeah i use typescript at google pretty much 100% of the time now. Its not a trivial rewrite but its getting closed to needing to be done because of refactor for  Buffer deprecations etc.

I'm interested in how you'ed like to expose umd but in general i expect people to use rollup/webpack themselves which have commonjs support already.

**Comment by JounQin** [comment]
In some companies, they would prefer CDN bundles for vendor packages.

**Comment by JounQin** [comment]
Just realized it did have umd format output. 🤣
https://unpkg.com/browse/qrcode@1.4.1/build/qrcode.js
