### ISSUE TITLE
1.5.0 should be semver-major

### ISSUE THREAD

**Issue by matthewmayer** [soldair/node-qrcode#287]
If you're dropping support for older node versions, shouldnt latest release be semver-major ie 2.0.0 not 1.5.0?

**Comment by wang1212** [comment]
At the same time, I hope to update **CHANGELOG.md**.

**Comment by soldair** [comment]
In general i agree. it's been about a year since those prs were landed in master but not published so it slipped by.

Another thing is I don't test on older nodejs versions. in a lot of cases its not possible given the range of nodejs versions the test frameworks themselves support. so its not practical to know until after a release is made to know if it's broken :scream: 

here is the nodejs projects support policy. Even 10 is unsupported.
https://nodejs.org/en/about/releases/

The counter argument is that semver describes the interface of a package not your runtime environment. https://semver.org/ 
I don't control your runtime. npm doesn't control your runtime.  A program you wrote while node 4 was supported will probably still work on the current supported nodejs versions without changes running with the new version 1.5.0 of qrcode. :heart: i think this is great.

You'll still have to opt in to the change by changing your range specifier in your package.json to accept the minor version. 
minor describes this as a change that doesn't make backwards incompatible changes to the api/interface.

Numbers are cheap and I'm not afraid to use them. But every old package has this problem. This package is older than one of my kids who is starting to program himself! :laughing: 

I'm really thankful for the opinions here. If i had caught it before publishing I might consider having this conversation before publishing but a great many of the folks not chiming in here have been running threads for a year requesting that i publish anything new at all.

As of now I intend to update the readme with a note about nodejs support pre 1.5.0 for users who find themselves in a situation where they cannot use a new nodejs but not publish 2.0 until ESM pocalipse is over.
