### ISSUE TITLE
incompatiable with electron js.

### ISSUE THREAD

**Issue by calidion** [soldair/node-qrcode#50]
module version mismatch. expected 49 got 46

**Comment by soldair** [comment]
interesting. this is a native module issue with canvas i expect.
this can be used client side in electron i bet because it has canvas built into it.

to make it work you probably need to follow these instructions. or just ignore the build error and use the canvas from the dom. https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
