### ISSUE TITLE
retina friendly

### ISSUE THREAD

**Issue by markbrown4** [soldair/node-qrcode#79]
Is it possible to add scaling depending on devicePixelRatio for the browser renderer?

**Comment by vigreco** [comment]
Hi @markbrown4, you can use the [scale](https://github.com/soldair/node-qrcode/#scale) option to adjust the size:

```javascript
const moduleSize = 4 // Default size is 4 pixels
const scale =  moduleSize * window.devicePixelRatio

QRCode.toDataURL('text', { scale }, (err, url) => {
 // ...
})
```

**Comment by markbrown4** [comment]
Thanks @vigreco, works like a charm.

```
QRCode.toCanvas(canvas, 'text', { scale })
```

**Comment by lujjjh** [comment]
This is still not retina-friendly I suppose. The image looks blurry.

https://github.com/soldair/node-qrcode/blob/e60fd6d4cbd999fee2f10eeb5c55fa82cfbfafee/lib/renderer/canvas.js#L6-L10

The `width` and `height` attribute should be `size * window.devicePixelRatio` instead of `size`. BTW, I don't think that `clearCanvas` should overwrite the `style`.

**Comment by philiparvidsson** [comment]
Why isn't this fixed?

**Comment by philiparvidsson** [comment]
Workaround for anyone else:

```
    QRCode.toCanvas(canvas.current, url, { width: 183 * devicePixelRatio, margin: 4 })
    canvas.current.style.width = canvas.current.width / devicePixelRatio + "px"
    canvas.current.style.height = canvas.current.height / devicePixelRatio + "px"

```
