### ISSUE TITLE
How to force a specific width of a PNG image?

### ISSUE THREAD

**Issue by gajus** [soldair/node-qrcode#89]
There does not seem to be an option to force a specific width of a PNG image. Simply scaling the picture would result in blurry visual.

**Comment by vigreco** [comment]
Hi @gajus, at the moment there's no way to specify a width, but you could generate an higher resolution image using a bigger [scale](https://github.com/soldair/node-qrcode#scale) value. Then you could downscale the image to the desidered width if needed.

Other possible solution:
Since the qrcode is made of white and black pixels I think you can upscale the image without losing quality just by disabling pixel interpolation.

**Comment by gajus** [comment]
> Hi @gajus, at the moment there's no way to specify a width, but you could generate an higher resolution image using a bigger scale value. Then you could downscale the image to the desidered width if needed.

This is what I've ended up doing.

> Other possible solution:
> Since the qrcode is made of white and black pixels I think you can upscale the image without losing quality just by disabling pixel interpolation.

Will give this a shot.

**Comment by soldair** [comment]
@vigreco should we consider adding support for this resize call? may be a common enough ask for those who cant use svg or dont want to impment their own renderer on top of the bit array

**Comment by vigreco** [comment]
@gajus, a [width](https://github.com/soldair/node-qrcode#width) option is now available in `qrcode@1.1.0`.
Thanks!
