### ISSUE TITLE
White Space around QR code

### ISSUE THREAD

**Issue by mraiguo** [soldair/node-qrcode#90]
is there a reason (or a way to remove), the white space around the QR code,like this;
![image](https://user-images.githubusercontent.com/22299421/30430914-64e8e538-998f-11e7-9b6c-bf0a246ded01.png)
thanks!

**Comment by vigreco** [comment]
Hi @mraiguo,

the margin (4 white modules) is there because is required by QR code specs and it's part of the symbol itself. QR code readers use that margin to isolate the symbol and recognize it.

However you can remove it using the [margin](https://github.com/soldair/node-qrcode#margin) option and setting the value to `0`,
but for a better readability make sure the symbol has at least a little margin around it.
